[build]
  publish = "docs"
  command = ""   # force Netlify à ne rien exécuter

[functions]
  directory = "netlify/functions"

[context.production.environment]
  SKIP_GEOCODE = "1"

[build.environment]
  SKIP_GEOCODE = "1"