[build]
  command = "bash -lc \"python -m pip install --upgrade pip && if [ -f requirements-build.txt ]; then pip install -r requirements-build.txt; fi && python scripts/build_all.py\""
  publish = "docs"

[context.production.environment]
  SKIP_GEOCODE = "1"
